# Generated by Django 3.2.12 on 2022-04-03 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Моля въведете валиден номер във формат 0888112233', regex='^08[7-9][5-9][0-9]{6}$')]),
        ),
    ]
