# Generated by Django 3.2.12 on 2022-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
