# Generated by Django 3.2.12 on 2022-04-05 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userappmodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Моля въведете валиден номер във формат 0888112233', regex='^08[7-9][5-9][0-9]{6}$')]),
            preserve_default=False,
        ),
    ]
