# Generated by Django 3.2.12 on 2022-04-12 09:35

import autotrade.products.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Марка')),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Модел')),
                ('image', models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(2)], verbose_name='Изберете снимка до 2мб')),
                ('year', models.DateField(validators=[autotrade.products.validators.validate_future_date], verbose_name='Година на производство')),
                ('price', models.CharField(default='В очакване на цена', max_length=18)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('fuel', models.CharField(choices=[('Дизел', 'Дизел'), ('Бензин', 'Бензин'), ('Електрически', 'Електрически'), ('Хибрид', 'Хибрид'), ('Газ', 'Газ')], max_length=12, verbose_name='Гориво')),
                ('motor', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7000), django.core.validators.MinValueValidator(800)], verbose_name='Обем на двигател')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Марка')),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Модел')),
                ('image', models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(2)], verbose_name='Изберете снимка до 2мб')),
                ('year', models.DateField(validators=[autotrade.products.validators.validate_future_date], verbose_name='Година на производство')),
                ('price', models.CharField(default='В очакване на цена', max_length=18)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('motor_type', models.CharField(blank=True, choices=[('Кросов', 'Кросов'), ('Пистов', 'Пистов'), ('Чопър', 'Чопър')], max_length=6, null=True, verbose_name='Тип на мотора (незадължително поле)')),
                ('cooling', models.CharField(blank=True, choices=[('Въздушно', 'Въздушно'), ('Водно', 'Водно')], max_length=8, null=True, verbose_name='Вид охлаждане (незадължително поле)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Марка')),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Модел')),
                ('image', models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(2)], verbose_name='Изберете снимка до 2мб')),
                ('year', models.DateField(validators=[autotrade.products.validators.validate_future_date], verbose_name='Година на производство')),
                ('price', models.CharField(default='В очакване на цена', max_length=18)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('total_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общо тегло')),
                ('capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Товароносимост')),
                ('category', models.CharField(blank=True, choices=[('Ван', 'Ван'), ('Специален', 'Специален'), ('Строителна техника', 'Строителна техника')], max_length=18, null=True, verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutotradeCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.car')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.car',),
        ),
        migrations.CreateModel(
            name='AutotradeMotorcycle',
            fields=[
                ('motorcycle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.motorcycle')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.motorcycle',),
        ),
        migrations.CreateModel(
            name='AutotradeTruck',
            fields=[
                ('truck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.truck')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.truck',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_category', models.CharField(choices=[('Двигател', 'Двигател'), ('Скорости', 'Скорости'), ('КУПЕ', 'КУПЕ'), ('Други', 'Други')], max_length=8, verbose_name='Категория')),
                ('condition', models.CharField(choices=[('Ново', 'Ново'), ('Използвано', 'Използвано'), ('Разопаковано', 'Разопаковано')], max_length=12, verbose_name='Състояние')),
                ('catalog_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Каталожен номер')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(1)], verbose_name='Изберете снимка до 1мб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
