# Generated by Django 3.2.12 on 2022-04-03 16:34

import autotrade.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(2)], verbose_name='Изберете снимка до 2мб'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(2)], verbose_name='Изберете снимка до 2мб'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(upload_to='', validators=[autotrade.products.validators.MaxFileSizeInMbValidator(2)], verbose_name='Изберете снимка до 2мб'),
        ),
    ]
