# Generated by Django 3.2.12 on 2022-04-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutotradePart',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.part')),
            ],
            bases=('products.part',),
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(default='Полуоска', max_length=33),
            preserve_default=False,
        ),
    ]
