# Generated by Django 3.2.12 on 2022-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220418_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
