# Generated by Django 3.2.12 on 2022-04-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220403_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutotradeCar',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.car')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.car',),
        ),
        migrations.CreateModel(
            name='AutotradeMotorcycle',
            fields=[
                ('motorcycle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.motorcycle')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.motorcycle',),
        ),
        migrations.CreateModel(
            name='AutotradeTruck',
            fields=[
                ('truck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.truck')),
            ],
            options={
                'abstract': False,
            },
            bases=('products.truck',),
        ),
    ]
