# Generated by Django 3.2.12 on 2022-04-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220418_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='price',
        ),
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='price',
        ),
    ]
