# Generated by Django 3.2.12 on 2022-04-18 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220418_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(default='В очакване на цена', max_length=18),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price',
            field=models.CharField(default='В очакване на цена', max_length=18),
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='price',
            field=models.CharField(default='В очакване на цена', max_length=18),
        ),
    ]
